### PR TITLE
update cmd to connect to aks to use kubeadmin

### PR DESCRIPTION
**Pull request by thegovind**
- Update `cmdToConnectToCluster` to use `kubeadmin` so that you can bypass the [RBAC for AKS setup](https://learn.microsoft.com/en-us/azure/aks/manage-azure-rbac#integrate-azure-rbac-into-an-existing-cluster)

### CODE REVIEW

**Review by majguo — APPROVED** [review]
LGTM.

**Comment by majguo** [comment]
Hello @git4rk @edburns Could you pls take a look?

**Comment by thegovind** [comment]
> Hello @git4rk @edburns Could you pls take a look?

<bump>

**Review by edburns — APPROVED** [review]

**Comment by majguo** [comment]
Hello @thegovind You may close this PR as its duplicate https://github.com/WASdev/azure.liberty.aks/pull/71 has been merged.

**Pull request closed without merging**
